on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Apps token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v3.1.2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          release-type: simple
          command: github-release
          # skip-github-pull-request: true